apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yc-cloud-resources-exporter.fullname" . }}
  labels:
    {{- include "yc-cloud-resources-exporter.labels" . | nindent 4 }}
data:
  key.json: {{ .Values.yc.saKey | b64enc | quote }}
