apiVersion: v1
kind: Service
metadata:
  name: {{ include "yc-cloud-resources-exporter.fullname" . }}
  labels:
    {{- include "yc-cloud-resources-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.resourcesMetricsPort }}
      targetPort: resources
      protocol: TCP
      name: resources
    - port: {{ .Values.service.pricingMetricsPort }}
      targetPort: pricing
      protocol: TCP
      name: pricing
  selector:
    {{- include "yc-cloud-resources-exporter.selectorLabels" . | nindent 4 }}
